name: NIR 2025 Frontend CI

on:
    push:
        branches:
            - main

jobs:
    create-deployment-artifacts:
        name: Create deployment artifacts
        runs-on: ubuntu-latest
        outputs:
            deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}

        steps:
            - uses: actions/checkout@v4
            - name: Create deployment artifact
              env:
                  GITHUB_SHA: ${{ github.sha }}
              run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=.next *

            - name: Store artifact for distribution
              uses: actions/upload-artifact@v4
              with:
                  name: app-build
                  path: ${{ github.sha }}.tar.gz

            - name: Export deployment matrix
              id: export-deployment-matrix
              run: |
                  JSON="$(cat ./deployment.json)"
                  JSON="${JSON//'%'/'%25'}"
                  JSON="${JSON//$'\n'/'%0A'}"
                  JSON="${JSON//$'\r'/'%0D'}"
                  echo "::set-output name=deployment-matrix::$JSON"

    prepare-release-on-servers:
        name: "${{ matrix.server.name }}: Prepare release"
        runs-on: ubuntu-latest
        needs: create-deployment-artifacts
        strategy:
            matrix:
                server: ${{ fromJson(needs.create-deployment-artifacts.outputs.deployment-matrix) }}
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: app-build
            - name: Upload
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ matrix.server.ip }}
                  username: ${{ secrets.SERVER_KEY_PRODUCTION }}
                  password: ${{ secrets.SERVER_SECRET_PRODUCTION }}
                  port: ${{ matrix.server.port }}
                  source: ${{ github.sha }}.tar.gz
                  target: ${{ matrix.server.release_path }}/artifacts
            - name: Extract archive and create directories
              uses: appleboy/ssh-action@master
              env:
                  GITHUB_SHA: ${{ github.sha }}
                  APP_VERSION: ${{ matrix.server.version }}
                  BASE_PATH: ${{ matrix.server.release_path }}/releases/${{ matrix.server.version }}
                  ENV: ${{ secrets.ENV_PRODUCTION }}
                  HTACCESS: ${{ secrets.HTACCESS_PRODUCTION_LIVE }}

              with:
                  host: ${{ matrix.server.ip }}
                  username: ${{ secrets.SERVER_KEY_PRODUCTION }}
                  password: ${{ secrets.SERVER_SECRET_PRODUCTION }}
                  port: ${{ matrix.server.port }}
                  envs: GITHUB_SHA,ENV,HTACCESS,PACKAGE
                  script: |
                      mkdir -m 777 -p "${{ matrix.server.release_path }}/releases/${{ matrix.server.version }}"
                      tar xzf ${{ matrix.server.release_path }}/artifacts/${GITHUB_SHA}.tar.gz -C "${{ matrix.server.release_path }}/releases/${{ matrix.server.version }}"
                      cd ${{ matrix.server.release_path }}/releases/${{ matrix.server.version }}
                      printf "%s" "$ENV" > "${{ matrix.server.release_path }}/releases/${{ matrix.server.version }}/.env.production"
                      printf "%s" "$HTACCESS" > "${{ matrix.server.public_path }}/.htaccess"
                      npm install
                      npm run build
                      pm2 delete nir-next
                      pm2 start npm --name "nir-next" -- run start -- -p 3001
